### ISSUE TITLE
Self Subscribing

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/Subvid_stream_contracts#1]
This issue is in the Subvid repo as well [referencing issue](https://github.com/aditya172926/Subvid_stream/issues/9)
Right now the users have to subscribe to a creator's address to view its content.

This is true even if the user wants to view his/her own content. Subscribing to itself just results in paying yourself and the user does not lose any tokens.

Still, this is an overhead and should be resolved.
This might be moderately challenging, and if anyone wants to work on it, comment and let me know.

**Comment by SahilSingh177** [comment]
Please assign this issue to me.

**Comment by aditya172926** [comment]
Sure @SahilSingh177 you can work on this 👍

**Comment by aditya172926** [comment]
Hey @SahilSingh177 , how is your progress going on?

**Comment by SahilSingh177** [comment]
Hey @aditya172926.
I added the following lines of code. Please have a look at them.

![Screenshot (166)](https://user-images.githubusercontent.com/96344003/195954080-f75c8cd3-25cf-4965-8694-512149ba3254.png)

In line no.- 89 the user who adds any content will be saved as a Gold Tier in Subscribed Tier.

**Comment by aditya172926** [comment]
> Hey @aditya172926. I added the following lines of code. Please have a look at them and share your views.
> 
> ![Screenshot (166)](https://user-images.githubusercontent.com/96344003/195954080-f75c8cd3-25cf-4965-8694-512149ba3254.png)
> 
> In line no.- 89 the user who adds any content will be saved as a Gold Tier in Subscribed Tier.

Looks good to me @SahilSingh177 .

**Comment by aditya172926** [comment]
Make a PR if you want this to be included in the repo. Also make sure you do a git pull before, just to make sure there aren't any conflicts @SahilSingh177
