### ISSUE TITLE
Replacing Address with Readable Names

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/Subvid_stream_contracts#4]
On Web3 we do have our wallet addresses which uniquely identify us. But we as humans are very used to dealing with readable names.

![image](https://user-images.githubusercontent.com/54861484/195254970-0309806e-4491-49c9-a8d2-8aaa16f34e43.png)

Currently on the website as shown in the image above, we get the creator's address, which is hard to remember.
Make a feature to use names mapped to wallet addresses. Which eventually should return creator names to be displayed on the website.

If you require more understanding, let's chat!

**Comment by aditya172926** [comment]
The website link is here Subvid streams https://subvid-stream.vercel.app/

**Comment by aditya172926** [comment]
Hey @Arun89-crypto, it will be great if you can work on this.
I am assigning this to you. 👍

**Comment by Arun89-crypto** [comment]
PR created #8 
Also added some requirements.
@aditya172926

**Comment by aditya172926** [comment]
The frontend repo is now open for Hacktoberfest! You can work on your enhancements under relevant issues.
Please comment there as well so I can assign you the issue. @Arun89-crypto 
Frontend repo https://github.com/aditya172926/Subvid_stream

**Comment by Arun89-crypto** [comment]
Ok @aditya172926 I commented assign that issue till then working on it. And please merge this issue also because without that I won't be able to use the username mapping.
