### ISSUE TITLE
Adding support for Metamask Wallet

### ISSUE THREAD

**Issue by ocdbytes** [aditya172926/Subvid_stream_contracts#7]
Currently only Celo wallet is supported but mostly people use Metamask wallet especially the developers like me use Metamask for testing and production both. I wanted to add Metamask 🦊  support so that development process becomes smooth.

**Comment by aditya172926** [comment]
Yes, the major crowd is definitely on Metamask. You can work on the contracts for this issue as well.
I'll have to see what changes are done before merging it with an hacktoberfest label.

I am assigning this to you 👍 @Arun89-crypto

**Comment by Arun89-crypto** [comment]
Sir this change we have to do in the web repository. Is it also available for hacktoberfest ? Because we need to add this functionality in frontend part of the application.

**Comment by aditya172926** [comment]
I will open the frontend repository for the Hacktoberfest by end of the day. Then I will message you here when I create an issue in that repo. Then you can contribute in the frontend repository @Arun89-crypto 
If you want you can fork the repo and start working.

**Comment by Arun89-crypto** [comment]
Ok @aditya172926 I will start working on the web development part.
